<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.AspNetCore.WebPush" Version="2.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.12" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.6" />
    <PackageReference Include="Mysql.Data" Version="9.4.0" />
    <PackageReference Include="WebPush" Version="1.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Adria.Application\Adria.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Persistence\Scripts\*.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
